version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_informational_version: '5.2.1-b{build}'
skip_tags: true
os: Visual Studio 2017
configuration: Release
branches:
  only:
  - master
before_build:
  - nuget restore NHibernate.Logging.sln
build_script:
- ps: .\build.ps1
artifacts:
- path: artifacts\**\*.nupkg
nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true 
deploy:
  provider: NuGet
  api_key:
    secure: AlZb9RmiC8ciqIT8+BygQoiae07DdHKte0lnn8ZQgHgj25ZBi6hXLIe4UPeNJwnQ
  skip_symbols: false
  artifact: /.*\.nupkg/
notifications:
- provider: Email
  to:
  - christian.junk@geomatics.io
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false